# Generated by Django 4.0.4 on 2022-06-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pedido_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='frete',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
