# Generated by Django 4.0.4 on 2022-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pedido_frete_alter_pedido_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
