# Generated by Django 4.0.5 on 2022-06-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pedido_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('aprovado', 'Pagamento aprovado'), ('carrinho', 'Carrinho')], default='carrinho', max_length=50),
        ),
    ]
