# Generated by Django 4.0.5 on 2022-06-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pedido_data_pedido_produto_data_adicionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
